build:
  system_packages:
    - "libssl-dev"
  python_packages:
    - "torchaudio==2.2.1"
    - "soundfile==0.12.1"
    - "git+https://github.com/suno-ai/bark.git@refs/pull/391/head"
    - "faster-whisper==1.0.0"
    - "torch==2.2.1"
    - "nltk==3.8.1"
